stages:
  - test

# Job Linux Fedora - execução dos testes sem docker
web-test:
  stage: test
  image: ubuntu:latest
  tags:
    - docker
  before_script:
    # Instalação do Google Chrome
    - apt update -y && echo ...OK
    - apt install -y wget && echo ...OK
    - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && echo ...OK
    - dpkg -i google-chrome-stable_current_amd64.deb && echo ...OK
    - apt install --fix-broken -y && echo ...OK
    - google-chrome --version
    - rm google-chrome-stable_current_amd64.deb
    # Instalação do Python e dependências
    - apt install -y python3.10 python3-pip python3.10-venv && echo ...OK
    - python3 --version
    - python3 -m venv venv
    - source venv/bin/activate
    - pip3 install -r requirements.txt && echo ...OK
  script:
    - robot -d ./results -v BROWSER:headlesschrome ./tests

  artifacts:
    when: always
    paths:
      - ./results
    expire_in: 1 week

# Job Linux Fedora - execução dos testes em container docker
web-test-docker:
  stage: test
  image: registry.gitlab.com/delorean-challenge/robotframework-images:latest
  tags:
    - docker
  script:
    - robot -d ./results -v BROWSER:headlesschrome ./tests

  artifacts:
    when: always
    paths:
      - ./results
    expire_in: 1 week
