stages:
  - test

# Execução dos testes sem docker
web-test:
  image: fedora:39
  stage: test
  tags:
    - docker
  before_script:
    - dnf upgrade -y --refresh
    - dnf install -y python37 python3-pip chromedriver-114.0* chromium-114.0*
    - dnf clean all
    - chown root /usr/bin/chromedriver
    - chmod +x /usr/bin/chromedriver
    - chmod 755 /usr/bin/chromedriver
    - chromedriver --version
    - pip3 install -r requirements.txt
  script:
    - robot -d ./results -v BROWSER:headlesschrome ./tests

  artifacts:
    when: always
    paths:
      - ./results
    expire_in: 1 week

# Execução dos testes em container docker publicado no GitLab Registry
web-test-docker:
  image: registry.gitlab.com/delorean-challenge/robotframework-images:latest
  stage: test
  tags:
    - docker
  script:
    - robot -d ./results -v BROWSER:headlesschrome ./tests
  artifacts:
    when: always
    paths:
      - ./results
    expire_in: 1 week
