name: Automated Tests

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        options: --shm-size=2g

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Automated Tests
        run: robot -d results -v BROWSER:headlesschrome tests

      - name: Save Test Report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Test Report
          path: results
